title: Jiahui (Maggie) Xu
logo: assets/img/round_profile.png
description: >
  <a href="https://github.com/MaggieXxxx" target="_blank">GitHub</a> &nbsp;|&nbsp;
  <a href="https://www.linkedin.com/in/maggie-xu-65394617a/" target="_blank">LinkedIn</a> &nbsp;|&nbsp;
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

include:
  - assets/css/style.scss
