title: Jiahui (Maggie) Xu
logo: assets/img/round_profile.png
description: >
  <div style="text-align: center;">
    <a href="https://github.com/MaggieXxxx" target="_blank">GitHub</a> &nbsp;|&nbsp;
    <a href="https://www.linkedin.com/in/maggie-xu-65394617a/" target="_blank">LinkedIn</a> &nbsp;|&nbsp;
    <a href="mailto:maggiejiahuixu@gmail.com">Email</a>
  </div>
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

include:
  - assets/css/style.scss
